app:
  debug: true
  dbCache: redis  # "redis" or "memcached"
  expirationCach : 5 #Second
database:
  driver: mysql
  host: mysql
  port: 3306
  username: root
  password: 12345678
  database: nobaan

redis:
  scheme: tcp
  host: redis
  port: 6379

